# This file was generated by GoReleaser. DO NOT EDIT.
cask "goo" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "a02deceb6ab34d24c26663aafdae7ba6601ef966b6bdff07a82684589cd34eb3"
      url "https://github.com/OOG-Labs/goo/releases/download/v#{version}/goo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9e7162c98c385804d92294a75046ef05a4cf0dbab401410d1ad8288ad9897ef6"
      url "https://github.com/OOG-Labs/goo/releases/download/v#{version}/goo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fec656344760b820460cfe13ea752c3b12f6b93e82da930d1146f885883938f3"
      url "https://github.com/OOG-Labs/goo/releases/download/v#{version}/goo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f242dceb76910c06ec6c7bd70fa10605870f895861d8719823d9db38f64d27fe"
      url "https://github.com/OOG-Labs/goo/releases/download/v#{version}/goo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "goo"
  desc "Deploy applications to GOO (oog.app) from your terminal"
  homepage "https://oog.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goo"

  # No zap stanza required
end
