# This file was generated by GoReleaser. DO NOT EDIT.
cask "goo" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "d0bb396c18a58bc1045b821b7a3a39e7d37c854e06aca85ec3dae594367c4512"
      url "https://github.com/OOG-Labs/goo/releases/download/v#{version}/goo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ddc36fd7cd907d5f761147298e27b5de7d56d495347f6d038b8bb7f5e8b7c92"
      url "https://github.com/OOG-Labs/goo/releases/download/v#{version}/goo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d1d96a2fad6f8b3b1cdca2d050f27705b231e40a1a4975ab85e0cb6c8f15c095"
      url "https://github.com/OOG-Labs/goo/releases/download/v#{version}/goo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "012058bc4f49c02e7c747ff3c02a4aa0903bb18a9e3d950499a860628f72d135"
      url "https://github.com/OOG-Labs/goo/releases/download/v#{version}/goo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "goo"
  desc "Deploy applications to GOO (oog.app) from your terminal"
  homepage "https://oog.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goo"

  # No zap stanza required
end
