# This file was generated by GoReleaser. DO NOT EDIT.
cask "goo" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "b61e1a67af58826835cbc4e709cbf9f4011f5bbad93270d7553568785ab6cf5c"
      url "https://github.com/OOG-Labs/goo/releases/download/v#{version}/goo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dc78688f4e0e2fd75ae606dc716cba050a1cece514d3b67a89dab9e81614d68f"
      url "https://github.com/OOG-Labs/goo/releases/download/v#{version}/goo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9dacfaf5624cf53fef52ce6f9ee2580007fff417143a4013b83ad1e9efc5ed4b"
      url "https://github.com/OOG-Labs/goo/releases/download/v#{version}/goo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "41c8337c0a5119dc528239e550efe849426d2ef860c776c33c70d0815d10515a"
      url "https://github.com/OOG-Labs/goo/releases/download/v#{version}/goo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "goo"
  desc "Deploy applications to GOO (oog.app) from your terminal"
  homepage "https://oog.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goo"

  # No zap stanza required
end
